apiVersion: v1
kind: Service
metadata:
  name: chess-backend
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app: chess-backend
  ports:
    - port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      nodePort: {{ .Values.backend.service.nodePort }}
