apiVersion: apps/v1
kind: Deployment
metadata:
  name: chess-backend
  labels:
    app: chess-backend
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: chess-backend
  template:
    metadata:
      labels:
        app: chess-backend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "{{ .Values.backend.port }}"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend
          image: "{{ .Values.backend.image }}:{{ .Values.backend.tag }}"
          imagePullPolicy: Never
          ports:
            - containerPort: {{ .Values.backend.port }}
          env:
            - name: STOCKFISH_PATH
              value: {{ .Values.backend.env.stockfishPath }}
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.backend.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
