{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: chess-backend
  labels:
    app: chess-backend
  {{- if .Values.backend.serviceAccount.irsaRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.backend.serviceAccount.irsaRoleArn }}
  {{- end }}
{{- end }}
